package com.example.thornburydental.data.cds

import kotlinx.serialization.Serializable

/**
 * Structured symptom entry with category and severity indicator.
 */
@Serializable
data class SymptomItem(
    val id: String,
    val name: String,
    val category: String, // e.g., "Maxillofacial & Dental", "Systemic & Pain", "Airway & Swallowing"
    val isRedFlagTrigger: Boolean = false
)

/**
 * Patient vitals & clinical context for decision-support input.
 */
@Serializable
data class PatientVitalsContext(
    val ageYears: Int? = null,
    val sex: String? = null, // "Male", "Female", "Other"
    val durationDays: Int? = null,
    val painSeverity: Int? = null, // 1 to 10
    val temperatureCelsius: Float? = null,
    val bloodPressureSystolic: Int? = null,
    val bloodPressureDiastolic: Int? = null,
    val heartRateBpm: Int? = null,
    val patientAllergies: List<String> = emptyList(), // e.g. ["Penicillin", "Latex", "NSAIDs"]
    val medicalConditions: List<String> = emptyList() // e.g. ["Anticoagulated", "Bisphosphonate Therapy", "Type 2 Diabetes"]
)

/**
 * Full user query payload submitted to the CDS engine.
 */
@Serializable
data class SymptomInputQuery(
    val selectedSymptoms: List<SymptomItem> = emptyList(),
    val freeTextDescription: String = "",
    val vitalsContext: PatientVitalsContext = PatientVitalsContext()
)

/**
 * Retrieved clinical guideline passage with provenance metadata.
 */
@Serializable
data class RetrievedPassage(
    val id: String,
    val guidelineTitle: String,
    val sectionHeader: String,
    val passageContent: String,
    val version: String,
    val lastReviewedDate: String,
    val relevanceScore: Float
)

/**
 * Non-LLM hardcoded red flag safety escalation result.
 */
@Serializable
data class RedFlagResult(
    val hasRedFlag: Boolean,
    val redFlagReason: String? = null,
    val emergencyGuidance: String? = null,
    val recommendedActions: List<String> = emptyList()
)

/**
 * Versioned clinical knowledge base metadata.
 */
@Serializable
data class CorpusMetadata(
    val corpusId: String = "dentara-clinical-kb-v1",
    val title: String = "Dentara Offline Maxillofacial & Clinical Practice Guidelines",
    val version: String = "2026.09.1",
    val passageCount: Int = 120,
    val checksumSha256: String = "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    val lastUpdatedIso: String = "2026-09-17"
)

/**
 * Differential possibility item generated by CDS inference engine.
 */
@Serializable
data class DifferentialItem(
    val conditionName: String,
    val likelihoodTier: String, // "High Suspicion", "Moderate Possibility", "Consider Rule-out"
    val clinicalRationale: String,
    val citedPassageIds: List<String> = emptyList()
)

/**
 * Complete CDS output state including red flags, differentials, citations, and streaming text.
 */
sealed class CdsResponseState {
    object Idle : CdsResponseState()
    object ProcessingRetrieval : CdsResponseState()
    data class Generating(val partialText: String, val redFlagResult: RedFlagResult) : CdsResponseState()
    data class Complete(
        val fullText: String,
        val redFlagResult: RedFlagResult,
        val differentials: List<DifferentialItem>,
        val citedPassages: List<RetrievedPassage>,
        val corpusVersion: String,
        val inferenceTimeMs: Long
    ) : CdsResponseState()
    data class Error(val errorMessage: String) : CdsResponseState()
}
